DROP TABLE IF EXISTS fang;

CREATE TABLE fang (
    id INT PRIMARY KEY,
    place VARCHAR(40) NOT NULL
);

INSERT INTO fang
    (id, place)
VALUES
    (0, 'Zurzacher Thermalbad'),
    (1, 'Eglisau Rheinfart'),
    (2, 'Flaach und Schloss Berg a.l.'),
    (3, 'Irchel'),
    (4, 'Schloss Laufen Rheinfall'),
    (5, 'Husemer See Naturschutzgebiet'),
    (6, 'Kartause Ittingen'),
    (7, 'Baden Landvogteischloss'),
    (8, 'Kloster Fahr'),
    (9, 'Lägern'),
    (10, 'Regensberg'),
    (11, 'Flughafen'),
    (12, 'Winterthur Sammlung Reinhart'),
    (13, 'Technorama Oberwinterthur'),
    (14, 'Kyburg'),
    (15, 'Bremgarten'),
    (16, 'Zürcher Zoo'),
    (17, 'Küsnachter Tobel'),
    (18, 'Dübendorf Flugzeug-Museum'),
    (19, 'Pfannenstiel'),
    (20, 'Greifensee-Schiffahrt'),
    (21, 'Uster Industrie-Lehrpfad'),
    (22, 'Römerkastell Irgenhausen'),
    (23, 'Grüningen Botanischer Garten'),
    (24, 'Ritterhaus Bubikon'),
    (25, 'Bäretswil Dampfbahn Hinwil-Bauma'),
    (26, 'Bauma Guyer-Zeller-Wege'),
    (27, 'Bachtel'),
    (28, 'Affoltern a.A. Reformierte Kirche'),
    (29, 'Planetenweg'),
    (30, 'Felsenegg ob Adliswil'),
    (31, 'Zürich Rietberg-Museum'),
    (32, 'Rifferswil Seleger Moor'),
    (33, 'Kappel'),
    (34, 'Horgen Fähre'),
    (35, 'Au Weinbau-Museum'),
    (36, 'Höllgrotten'),
    (37, 'Ufenau'),
    (38, 'Rapperswil Kinderzoo'),
    (39, 'Einsiedeln'),
    (40, 'Koblenz'),
    (41, 'Kaiserstuhl'),
    (42, 'Eglisau <> Rafz'),
    (43, 'Rafz'),
    (44, 'Schaffhausen'),
    (45, 'Marthalen'),
    (46, 'Andelfingen'),
    (47, 'Ossingen'),
    (48, 'Seuzach'),
    (49, 'Stammheim'),
    (50, 'Technorama <> Frauenfeld'),
    (51, 'Stein am Rhein'),
    (52, 'Frauenfeld'),
    (53, 'Brugg'),
    (54, 'Niederweningen'),
    (55, 'Steinmaur'),
    (56, 'Dielsdorf'),
    (57, 'Bülach'),
    (58, 'Oberglatt'),
    (59, 'Embrach'),
    (60, 'Pfungen'),
    (61, 'Pfungen <> Winterthur'),
    (62, 'Aadorf'),
    (63, 'Wil'),
    (64, 'Wettingen'),
    (65, 'Otelfingen'),
    (66, 'Regensdorf'),
    (67, 'Regensdorf <> Oerlikon'),
    (68, 'Oerlikon'),
    (69, 'Oerlikon <> Oberglatt'),
    (70, 'Kloten'),
    (71, 'Wallisellen'),
    (72, 'Bassersdorf'),
    (73, 'Dietlikon'),
    (74, 'Effretikon'),
    (75, 'Kemptthal'),
    (76, 'Winterthur Seen'),
    (77, 'Sennhof'),
    (78, 'Sennhof <> Guyer-Zeller-Wege'),
    (79, 'Wettingen <> Dietikon'),
    (80, 'Dietikon'),
    (81, 'Wohlen'),
    (82, 'Berikon-Widen'),
    (83, 'Altstetten'),
    (84, 'Hardbrücke'),
    (85, 'Zürich HB'),
    (86, 'Stadelhofen'),
    (87, 'Stettbach'),
    (88, 'Nänikon-Greifensee'),
    (89, 'Effretikon <> Pfäffikon ZH'),
    (90, 'Pfäffikon ZH'),
    (91, 'Pfäffikon ZH <> Wetzikon'),
    (92, 'Bauma <> Wald'),
    (93, 'Birmensdorf'),
    (94, 'Birmensdorf <> Altstetten'),
    (95, 'Uitikon-Waldegg'),
    (96, 'Selnau'),
    (97, 'Wiedikon'),
    (98, 'Enge'),
    (99, 'Enge <> Stadelhofen'),
    (100, 'Enge <> Thalwil'),
    (101, 'Thalwil'),
    (102, 'Stadelhofen <> Küsnachter Tobel'),
    (103, 'Zumikon'),
    (104, 'Küsnachter Tobel <> Meilen'),
    (105, 'Meilen'),
    (106, 'Forch'),
    (107, 'Egg'),
    (108, 'Esslingen'),
    (109, 'Uster <> Wetzikon'),
    (110, 'Wetzikon'),
    (111, 'Hinwil'),
    (112, 'Wald'),
    (113, 'Rüti ZH'),
    (114, 'Birmensdorf <> Affoltern a.A.'),
    (115, 'Üetliberg'),
    (116, 'Selnau <> Adliswil'),
    (117, 'Adliswil'),
    (118, 'Langnau-G.'),
    (119, 'Affoltern a.A. <> Zug'),
    (120, 'Zug'),
    (121, 'Baar'),
    (122, 'Sihlbrugg'),
    (123, 'Wädenswil'),
    (124, 'Wädenswil <> Pfäffikon SZ'),
    (125, 'Pfäffikon SZ'),
    (126, 'Pfäffikon SZ <> Ziegelbrücke'),
    (127, 'Ziegelbrücke'),
    (128, 'Wädenswil <> Schindellegi'),
    (129, 'Schindellegi'),
    (130, 'Meilen <> Männedorf'),
    (131, 'Männedorf'),
    (132, 'Männedorf <> Rapperswil');

CREATE INDEX ByPlace ON fang
    USING hash (place);
